apiVersion: v1
kind: Pod
metadata:
  name: tailbench-iperf3
  labels:
    app: tailbench-iperf3
spec:
  nodeSelector:
    topology.kubernetes.io/zone: REPLACE_AZ
  terminationGracePeriodSeconds: 5
  containers:
  - name: iperf3
    image: networkstatic/iperf3:latest
    command: ["iperf3", "-s", "-p", "15201"]
    ports:
    - containerPort: 15201
      protocol: TCP
    resources:
      requests:
        cpu: "2"
        memory: "1Gi"
      limits:
        cpu: "4"
        memory: "2Gi"
