#!/usr/bin/env bash
# Test parameters

IPERF_DURATION="${IPERF_DURATION:-30}"
IPERF_PARALLEL="${IPERF_PARALLEL:-4}"
IPERF_ITERATIONS="${IPERF_ITERATIONS:-3}"
MTR_CYCLES="${MTR_CYCLES:-100}"
INSTANCE_PREFIX="${INSTANCE_PREFIX:-tb}"
SSH_TIMEOUT=60
SSH_RETRIES=30
READY_TIMEOUT=300
AUTHKEY_REFRESH_INTERVAL=1800  # 30 minutes
