#!/usr/bin/env bash
# EKS configuration

EKS_CLUSTER_NAME="${EKS_CLUSTER_NAME:-tailbench-eks}"
EKS_NAMESPACE="${EKS_NAMESPACE:-tailbench}"
EKS_NODE_INSTANCE_TYPE="${EKS_NODE_INSTANCE_TYPE:-m5.xlarge}"
EKS_SUBNET_CIDR="${EKS_SUBNET_CIDR:-10.0.2.0/24}"
EKS_SUBNET_CIDR_AZ2="${EKS_SUBNET_CIDR_AZ2:-10.0.3.0/24}"
